name: selforder
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2 # State management/route
  toastification: ^3.0.3 # Toast Notification
  infinite_scroll_pagination: ^4.0.0 #Paggination API
  cupertino_icons: ^1.0.2 # Icons IOS
  intl: ^0.20.2 # Format tanggal/mata uang
  http: ^1.1.0 # Call API
  url_launcher: ^6.2.5 # Open URL
  google_sign_in: ^6.1.6 # Google Auth Sign-in
  open_file: ^3.5.10 # Open File PDF
  permission_handler: ^11.3.1 # Izin akses Android/Ios
  shared_preferences: ^2.5.3 # Simpan data lokal
  path_provider: ^2.1.5 # Akses Directory Device
  firebase_core: ^4.1.1 # firebase core
  firebase_auth: ^6.1.0 # firebase auth
  firebase_messaging: ^16.0.4 # firebase messaging

  
dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/cafe.png"
  min_sdk_android: 28
  web:
    generate: true
    image_path: "assets/images/cafe.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/cafe.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/cafe.png"

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/cafe.png
    - assets/images/google.png
